const test=require('node:test'),assert=require('node:assert/strict'),zlib=require('node:zlib');
const A=require('../scripts/airborne');
const concat=(...a)=>Buffer.concat(a.map(x=>Buffer.from(x)));
const req=()=>A.frame(concat(A.f(1,170001),A.f(2,12345),A.f(3,1),A.f(4,1)));
const row=(category='sponsor',segment=[10,30],cid='12345')=>({category,segment,cid,actionType:'skip'});
const cfg=A.config({});
function env(opts={}){let calls=[],done=[],store={},timers=new Map(),n=0;const e={
 $argument:opts.argument||{},$request:{url:'https://grpc.biliapi.net/bilibili.community.service.dm.v1.DM/DmSegMobile',method:'POST',headers:{},body:req()},
 $persistentStore:{read:k=>store[k],write:(v,k)=>{store[k]=v;return true;}},
 $httpClient:{get:(o,cb)=>{calls.push(o);cb(null,{status:200},JSON.stringify([row()]));},post:(o,cb)=>{calls.push(o);cb(null,{status:200,headers:{'Content-Type':'application/grpc'},h2_trailers:{'grpc-status':'0'}},A.frame(A.f(99,'unknown')));}},
 $done:o=>done.push(o),setTimeout:(fn,ms)=>{timers.set(++n,fn);return n;},clearTimeout:id=>timers.delete(id),$utils:{ungzip:b=>new Uint8Array(zlib.gunzipSync(b))}
 };return {e,calls,done,store,timers};}
test('BV conversion known vector',()=>assert.equal(A.bv(170001),'BV17x411w7KC'));
test('all eight categories and explicit disabled',()=>{for(const cat of A.CATS){let c=A.config(Object.fromEntries(A.CATS.map(x=>[x,x===cat])));assert.equal(A.normalize([row(cat)],12345,c).length,1);}assert.equal(A.normalize([row('intro')],12345,cfg).length,0);});
test('strict validation, CID, action, minimum and offset',()=>{let rows=[row(),row('sponsor',[NaN,20]),row('sponsor',[-2,10]),row('sponsor',[20,10]),row('sponsor',[1,'20']),row('sponsor',[1,3]),row('sponsor',[10,40],'999'),{...row(),actionType:'mute'},row('bad')];assert.deepEqual(A.normalize(rows,12345,cfg),[[12000,30000]]);});
test('sorting duplicate and overlap merge',()=>assert.deepEqual(A.normalize([row('sponsor',[20,50]),row('sponsor',[10,30]),row('sponsor',[10,30])],12345,A.config({offset:0})),[[10000,50000]]));
test('config bounds and numeric fallback',()=>{let c=A.config({minDuration:'bad',cacheCapacity:10000,cacheTTL:0,offset:-100});assert.equal(c.min,8);assert.equal(c.capacity,256);assert.equal(c.ttl,60000);assert.equal(c.offset,-10);});
test('wire parser preserves unknown fixed and varint fields',()=>{let b=concat(A.f(99,'retained'),A.f(100,999),Uint8Array.of(13,1,2,3,4));assert.deepEqual(concat(...A.fields(b).map(f=>f.raw)),b);});
test('protobuf rejects truncated varints lengths illegal tags groups',()=>{for(const b of [[128],[10,255],[0],[11],[9,1],[8,...Array(10).fill(255)]])assert.throws(()=>A.fields(Uint8Array.from(b)));});
test('grpc uncompressed multiple and gzip frames',()=>{let p=A.f(1,'x'),gz=zlib.gzipSync(p),g=concat(Uint8Array.of(1,0,0,0,gz.length),gz);assert.equal(A.frames(concat(A.frame(p),g),'gzip',b=>new Uint8Array(zlib.gunzipSync(b))).length,2);assert.throws(()=>A.frames(g,'br',b=>b));assert.throws(()=>A.frames(g,'gzip',null));});
test('grpc truncated flags oversized empty no-op boundaries',()=>{for(const b of [[],[0],[0,0,0,0,2,1],[2,0,0,0,0]])assert.throws(()=>A.frames(Uint8Array.from(b)));assert.throws(()=>A.frames(new Uint8Array(4194305)));});
test('injection retains original bytes and does not double inject',()=>{let p=A.f(99,'untouched'),q=A.inject(p,[[12000,30000]],12345);assert.deepEqual(Buffer.from(q.slice(0,p.length)),Buffer.from(p));assert.deepEqual(A.inject(q,[[12000,30000]],12345),q);let elem=A.fields(A.fields(q)[1].v);assert.equal(new TextDecoder().decode(elem.find(x=>x.no===7).v),'空指部已就位');assert.equal(new TextDecoder().decode(elem.find(x=>x.no===10).v),'airborne:30000');});
test('cache TTL capacity corruption and storage failures',()=>{let m={};let s={read:k=>m[k],write:(v,k)=>m[k]=v};A.cacheSave(s,[{k:'a',t:1,rows:[]},{k:'b',t:1000,rows:[]},{k:'c',t:2000,rows:[]}]);let c={ttl:2000,capacity:1};assert.equal(A.cacheLoad(s,2500,c)[0].k,'c');m[A.KEY]='bad';assert.deepEqual(A.cacheLoad(s,2500,c),[]);assert.doesNotThrow(()=>A.cacheSave({write(){throw Error();}},[]));});
test('Chronos only allowlist and retains guide dm unknown fields',()=>{let md=Object.keys(A.MODULES)[0],p=concat(A.f(1,'guide'),A.f(2,concat(A.f(1,md),A.f(2,'old'),A.f(3,'signature'),A.f(99,'keep'))),A.f(4,'dm'));let out=A.fields(A.chronos(p));assert.equal(new TextDecoder().decode(out[0].v),'guide');assert.equal(new TextDecoder().decode(out[2].v),'dm');assert.equal(A.fields(out[1].v).some(x=>x.no===3),false);assert.equal(A.fields(out[1].v).some(x=>x.no===99),true);assert.equal(A.chronos(A.f(2,concat(A.f(1,'unknown'),A.f(2,'old')))),null);});
test('Loon success done exactly once and cache hit avoids API',async()=>{let v=env();await A.run(v.e);assert.equal(v.done.length,1);assert.ok(v.done[0].response);assert.equal(v.calls.length,2);await A.run(v.e);assert.equal(v.calls.length,3);assert.equal(v.done.length,2);});
test('multi-category request uses correct query and isolated cache',async()=>{let v=env({argument:{intro:true}});await A.run(v.e);assert.deepEqual(JSON.parse(new URL(v.calls[0].url).searchParams.get('categories')),['sponsor','intro']);v.e.$argument={intro:false};await A.run(v.e);assert.equal(v.calls.length,4);});
test('segment-index only injects current six-minute partition',async()=>{let v=env();v.e.$request.body=A.frame(concat(A.f(1,170001),A.f(2,12345),A.f(3,1),A.f(4,2)));await A.run(v.e);assert.deepEqual(v.done,[{}]);assert.equal(v.calls.length,1);});
test('404 negative cache and HTTP 500 never injected',async()=>{for(const status of [404,500]){let v=env();v.e.$httpClient.get=(o,cb)=>{v.calls.push(o);cb(null,{status},'');};await A.run(v.e);await A.run(v.e);assert.deepEqual(v.done,[{},{}]);assert.equal(v.calls.length,status===404?1:2);}});
test('malformed JSON network errors binary failures storage throw all fail-open',async()=>{for(const mutate of [e=>e.$httpClient.get=(o,cb)=>cb(null,{status:200},'{'),e=>e.$httpClient.get=(o,cb)=>cb('error'),e=>e.$httpClient.post=(o,cb)=>cb(null,{status:200},Uint8Array.of(0)),e=>e.$persistentStore.read=()=>{throw Error();},e=>e.$request.body=Uint8Array.of(1)]){let v=env();mutate(v.e);await A.run(v.e);assert.equal(v.done.length,1);if(v.done[0].response)assert.equal(v.calls.length,2);else assert.deepEqual(v.done[0],{});}});
test('unsupported multi request and response frames fail-open',async()=>{let v=env();v.e.$request.body=concat(req(),req());await A.run(v.e);assert.deepEqual(v.done,[{}]);v=env();v.e.$httpClient.post=(o,cb)=>cb(null,{status:200},concat(A.frame(A.f(99,'a')),A.frame(A.f(99,'b'))));await A.run(v.e);assert.deepEqual(v.done,[{}]);});
test('late callback after timer done only once',async()=>{let v=env(),cb;v.e.$httpClient.get=(o,c)=>cb=c;let p=A.run(v.e);for(const fn of [...v.timers.values()])fn();cb(null,{status:200},'[]');await p;assert.deepEqual(v.done,[{}]);});
test('disabled performs zero requests',async()=>{let v=env({argument:{enabled:false}});await A.run(v.e);assert.equal(v.calls.length,0);assert.deepEqual(v.done,[{}]);});
test('Loon ViewProgress success preserves unrelated fields',async()=>{let v=env();v.e.$request.url='https://app.bilibili.com/bilibili.app.viewunite.v1.View/ViewProgress';v.e.$response={status:200,headers:{},body:A.frame(concat(A.f(4,'dm'),A.f(2,concat(A.f(1,Object.keys(A.MODULES)[0]),A.f(2,'old')))))};await A.run(v.e);assert.equal(v.done.length,1);assert.ok(v.done[0].body);assert.equal(v.calls.length,0);});
