const test=require('node:test'),assert=require('node:assert/strict'),zlib=require('node:zlib');
const A=require('../scripts/airborne');
const concat=(...a)=>Buffer.concat(a.map(x=>Buffer.from(x)));
const req=()=>A.frame(concat(A.f(1,170001),A.f(2,12345),A.f(3,1),A.f(4,1)));
const row=(category='sponsor',segment=[10,30],cid='12345')=>({category,segment,cid,actionType:'skip'});
const cfg=A.config({});
function env(opts={}){let calls=[],done=[],store={},timers=new Map(),n=0;const e={
 $argument:opts.argument||{},$request:{url:'https://grpc.biliapi.net/bilibili.community.service.dm.v1.DM/DmSegMobile',method:'POST',headers:{},body:req()},
 $persistentStore:{read:k=>store[k],write:(v,k)=>{store[k]=v;return true;}},
 $httpClient:{get:(o,cb)=>{calls.push({...o,method:'GET'});cb(null,{status:200},JSON.stringify([row()]));},post:(o,cb)=>{calls.push({...o,method:'POST'});cb(null,{status:200,headers:{'Content-Type':'application/grpc'},h2_trailers:{'grpc-status':'0'}},A.frame(A.f(99,'unknown')));}},
 $done:o=>done.push(o),setTimeout:(fn,ms)=>{timers.set(++n,fn);return n;},clearTimeout:id=>timers.delete(id),$utils:{ungzip:b=>new Uint8Array(zlib.gunzipSync(b))}
 };return {e,calls,done,store,timers};}
test('BV conversion known vector',()=>assert.equal(A.bv(170001),'BV17x411w7KC'));
test('all eight categories and explicit disabled',()=>{for(const cat of A.CATS){let c=A.config(Object.fromEntries(A.CATS.map(x=>[x,x===cat])));assert.equal(A.normalize([row(cat)],12345,c).length,1);}assert.equal(A.normalize([row('intro')],12345,cfg).length,0);});
test('strict validation, CID, action, minimum and offset',()=>{let rows=[row(),row('sponsor',[NaN,20]),row('sponsor',[-2,10]),row('sponsor',[20,10]),row('sponsor',[1,'20']),row('sponsor',[1,3]),row('sponsor',[10,40],'999'),{...row(),actionType:'mute'},row('bad')];assert.deepEqual(A.normalize(rows,12345,cfg),[[12000,30000]]);});
test('sorting duplicate and overlap merge',()=>assert.deepEqual(A.normalize([row('sponsor',[20,50]),row('sponsor',[10,30]),row('sponsor',[10,30])],12345,A.config({offset:0})),[[10000,50000]]));
test('config bounds and numeric fallback',()=>{let c=A.config({minDuration:'bad',cacheCapacity:10000,cacheTTL:0,offset:-100});assert.equal(c.min,8);assert.equal(c.capacity,256);assert.equal(c.ttl,60000);assert.equal(c.offset,-10);});
test('wire parser preserves unknown fixed and varint fields',()=>{let b=concat(A.f(99,'retained'),A.f(100,999),Uint8Array.of(13,1,2,3,4));assert.deepEqual(concat(...A.fields(b).map(f=>f.raw)),b);});
test('protobuf rejects truncated varints lengths illegal tags groups',()=>{for(const b of [[128],[10,255],[0],[11],[9,1],[8,...Array(10).fill(255)]])assert.throws(()=>A.fields(Uint8Array.from(b)));});
test('grpc uncompressed multiple and gzip frames',()=>{let p=A.f(1,'x'),gz=zlib.gzipSync(p),g=concat(Uint8Array.of(1,0,0,0,gz.length),gz);assert.equal(A.frames(concat(A.frame(p),g),'gzip',b=>new Uint8Array(zlib.gunzipSync(b))).length,2);assert.throws(()=>A.frames(g,'br',b=>b));assert.throws(()=>A.frames(g,'gzip',null));});
test('grpc truncated flags oversized empty no-op boundaries',()=>{for(const b of [[],[0],[0,0,0,0,2,1],[2,0,0,0,0]])assert.throws(()=>A.frames(Uint8Array.from(b)));assert.throws(()=>A.frames(new Uint8Array(4194305)));});
test('injection retains original bytes and does not double inject',()=>{let p=A.f(99,'untouched'),q=A.inject(p,[[12000,30000]],12345);assert.deepEqual(Buffer.from(q.slice(0,p.length)),Buffer.from(p));assert.deepEqual(A.inject(q,[[12000,30000]],12345),q);let elem=A.fields(A.fields(q)[1].v);assert.equal(new TextDecoder().decode(elem.find(x=>x.no===7).v),'空指部已就位');assert.equal(new TextDecoder().decode(elem.find(x=>x.no===10).v),'airborne:30000');});
test('cache TTL capacity corruption and storage failures',()=>{let m={};let s={read:k=>m[k],write:(v,k)=>m[k]=v};A.cacheSave(s,[{k:'a',t:1,rows:[]},{k:'b',t:1000,rows:[]},{k:'c',t:2000,rows:[]}]);let c={ttl:2000,capacity:1};assert.equal(A.cacheLoad(s,2500,c)[0].k,'c');m[A.KEY]='bad';assert.deepEqual(A.cacheLoad(s,2500,c),[]);assert.doesNotThrow(()=>A.cacheSave({write(){throw Error();}},[]));});
test('Chronos only allowlist and retains guide dm unknown fields',()=>{let md=Object.keys(A.MODULES)[0],p=concat(A.f(1,'guide'),A.f(2,concat(A.f(1,md),A.f(2,'old'),A.f(3,'signature'),A.f(99,'keep'))),A.f(4,'dm'));let out=A.fields(A.chronos(p));assert.equal(new TextDecoder().decode(out[0].v),'guide');assert.equal(new TextDecoder().decode(out[2].v),'dm');assert.equal(A.fields(out[1].v).some(x=>x.no===3),false);assert.equal(A.fields(out[1].v).some(x=>x.no===99),true);assert.equal(A.chronos(A.f(2,concat(A.f(1,'0123456789abcdef0123456789abcdef'),A.f(2,'old')))),null);});
test('Loon success done exactly once and cache hit avoids API',async()=>{let v=env();await A.run(v.e);assert.equal(v.done.length,1);assert.ok(v.done[0].response);assert.equal(v.calls.length,2);await A.run(v.e);assert.equal(v.calls.length,3);assert.equal(v.done.length,2);});
test('multi-category request uses correct query and isolated cache',async()=>{let v=env({argument:{intro:true}});await A.run(v.e);assert.deepEqual(JSON.parse(new URL(v.calls.find(o=>o.method==='GET').url).searchParams.get('categories')),['sponsor','intro']);v.e.$argument={intro:false};await A.run(v.e);assert.equal(v.calls.length,4);assert.deepEqual(v.calls.filter(o=>o.method==='GET').map(o=>JSON.parse(new URL(o.url).searchParams.get('categories'))),[['sponsor','intro'],['sponsor']]);});
function assertOriginalReply(result){assert.ok(result.response);assert.equal(result.response.status,200);assert.deepEqual(result.response.headers,{'Content-Type':'application/grpc'});assert.deepEqual(result.response.h2_trailers,{'grpc-status':'0'});assert.deepEqual(Buffer.from(result.response.body),Buffer.from(A.frame(A.f(99,'unknown'))));assert.equal(A.fields(A.frames(result.response.body)[0]).some(x=>x.no===1),false);}
test('segment-index only injects current six-minute partition',async()=>{let v=env();v.e.$request.body=A.frame(concat(A.f(1,170001),A.f(2,12345),A.f(3,1),A.f(4,2)));await A.run(v.e);assert.equal(v.done.length,1);assertOriginalReply(v.done[0]);assert.equal(v.calls.length,2);await A.run(v.e);assert.deepEqual(v.done[1],{});assert.equal(v.calls.length,2);});
test('404 negative cache and HTTP 500 never injected',async()=>{for(const status of [404,500]){let v=env();v.e.$httpClient.get=(o,cb)=>{v.calls.push({...o,method:'GET'});cb(null,{status},'');};await A.run(v.e);assert.equal(v.done.length,1);assertOriginalReply(v.done[0]);await A.run(v.e);assert.equal(v.done.length,2);if(status===404)assert.deepEqual(v.done[1],{});else assertOriginalReply(v.done[1]);assert.equal(v.calls.filter(o=>o.method==='GET').length,status===404?1:2);assert.equal(v.calls.filter(o=>o.method==='POST').length,status===404?1:2);}});
test('malformed JSON network errors binary failures storage throw all fail-open',async()=>{for(const failure of ['json','network','binary','storage','request']){let v=env();if(failure==='json'||failure==='network')v.e.$httpClient.get=(o,cb)=>{v.calls.push({...o,method:'GET'});if(failure==='json')cb(null,{status:200},'{');else cb('error');};if(failure==='binary')v.e.$httpClient.post=(o,cb)=>{v.calls.push({...o,method:'POST'});cb(null,{status:200},Uint8Array.of(0));};if(failure==='storage')v.e.$persistentStore.read=()=>{throw Error();};if(failure==='request')v.e.$request.body=Uint8Array.of(1);await A.run(v.e);assert.equal(v.done.length,1);assert.equal(v.calls.length,failure==='request'?0:2);if(failure==='json'||failure==='network')assertOriginalReply(v.done[0]);else if(failure==='storage'){assert.ok(v.done[0].response);assert.deepEqual(Buffer.from(v.done[0].response.body),Buffer.from(A.frame(A.inject(A.f(99,'unknown'),[[12000,30000]],12345))));}else assert.deepEqual(v.done[0],{});}});
test('unsupported multi request and response frames fail-open',async()=>{let v=env();v.e.$request.body=concat(req(),req());await A.run(v.e);assert.deepEqual(v.done,[{}]);v=env();v.e.$httpClient.post=(o,cb)=>cb(null,{status:200},concat(A.frame(A.f(99,'a')),A.frame(A.f(99,'b'))));await A.run(v.e);assert.deepEqual(v.done,[{}]);});
test('late callback after timer done only once',async()=>{let v=env(),cb;v.e.$httpClient.get=(o,c)=>cb=c;let p=A.run(v.e);for(const fn of [...v.timers.values()])fn();cb(null,{status:200},'[]');await p;assert.deepEqual(v.done,[{}]);});
test('disabled performs zero requests',async()=>{let v=env({argument:{enabled:false}});await A.run(v.e);assert.equal(v.calls.length,0);assert.deepEqual(v.done,[{}]);});
test('independent mode handles ViewProgress with known module',async()=>{let v=env();v.e.$request.url='https://app.bilibili.com/bilibili.app.viewunite.v1.View/ViewProgress';v.e.$response={status:200,headers:{},body:A.frame(concat(A.f(4,'dm'),A.f(2,concat(A.f(1,Object.keys(A.MODULES)[0]),A.f(2,'old')))))};await A.run(v.e);assert.ok(v.done[0].body);assert.equal(v.done.length,1);assert.equal(v.calls.length,0);});
test('safe diagnostics default off and explicit on contain no identifiers',async()=>{const required=['request-matched','cache-miss','grpc-start','grpc-end','query-start','query-end','filter','grpc-injected','total'];const safe=/^\[airborne diag-v1\] (?:request-matched|cache-miss|grpc-start|query-start|grpc-end ms=\d+ http=200|query-end ms=\d+ http=200|filter filter=1|grpc-injected filter=1 grpc=\d+|total ms=\d+)$/;for(const diagnostics of [undefined,false,true]){let v=env({argument:diagnostics===undefined?{}:{diagnostics}}),logs=[];v.e.$request.headers={Authorization:'secret-token',Cookie:'identity-cookie'};v.e.console={log:s=>logs.push(s)};await A.run(v.e);if(!diagnostics)assert.deepEqual(logs,[]);else{const events=logs.map(s=>s.replace('[airborne diag-v1] ','').split(' ')[0]);for(const event of required)assert.equal(events.filter(x=>x===event).length,1,`required event ${event}`);assert.equal(events.at(-1),'total');}for(const s of logs){assert.match(s,safe);assert.doesNotMatch(s,/12345|170001|BV17|https|token|secret|Authorization|cookie|identity/i);}}});
test('plugin registers exactly one dual-path response and request',()=>{const s=require('node:fs').readFileSync(require('node:path').join(__dirname,'../BilibiliAirborne.plugin'),'utf8');assert.equal((s.match(/^response /gm)||[]).length,1);assert.equal((s.match(/^request /gm)||[]).length,1);assert.match(s,/view\|viewunite/);assert.match(s,/module = select,"auto","universal","hd","inter"/);assert.match(s,/diagnostics = switch,false/);assert.match(s,/\$\{module\}/);});

function responseEnv({path='view',md5='0123456789abcdef0123456789abcdef',ua='bili-universal/1',argument={},gzip=false}={}){const v=env({argument});v.logs=[];v.e.console={log:s=>v.logs.push(s)};v.e.$request.url=`https://app.bilibili.com/bilibili.app.${path}.v1.View/ViewProgress`;v.e.$request.headers={'User-Agent':ua,Authorization:'secret-token'};const p=concat(A.f(1,'guide'),A.f(2,concat(A.f(1,md5),A.f(2,'https://private/?token=secret'),A.f(3,'signature'),A.f(99,'unknown'))),A.f(4,'dm'));let body=A.frame(p);if(gzip){let gz=zlib.gzipSync(p);body=concat(Uint8Array.of(1,(gz.length>>>24)&255,(gz.length>>>16)&255,(gz.length>>>8)&255,gz.length&255),gz);}v.e.$response={status:200,headers:{'grpc-encoding':gzip?'gzip':'identity','Content-Length':String(body.length),'Content-Type':'application/grpc'},h2_trailers:{'grpc-status':'0'},body};return v;}
function selected(v){const p=A.frames(v.done[0].body,'identity')[0];const cs=A.fields(p).find(x=>x.no===2);return new TextDecoder().decode(A.fields(cs.v).find(x=>x.no===1).v);}
test('response full paths gzip UA fallback preserves fields removes sign',async()=>{for(const path of ['view','viewunite'])for(const gzip of [false,true])for(const [ua,md] of [['bili-universal/8','e5a968f1a5055bbe5c12e67b100a6dcb'],['bili-hd/3','f993a054969a4f6ae6b20a65f1292e47'],['bili-inter/3','8c3feda2e92bf60e8a7aeade1a231586'],['Bilibili/8','e5a968f1a5055bbe5c12e67b100a6dcb'],['bili/8','e5a968f1a5055bbe5c12e67b100a6dcb']]){let v=responseEnv({path,gzip,ua,argument:{diagnostics:true}});await A.run(v.e);assert.equal(v.done.length,1);assert.equal(selected(v),md);assert.equal(v.calls.length,0);let fs=A.fields(A.frames(v.done[0].body,'identity')[0]);assert.equal(new TextDecoder().decode(fs[0].v),'guide');assert.equal(new TextDecoder().decode(fs[2].v),'dm');let inner=A.fields(fs[1].v);assert.equal(inner.some(x=>x.no===3),false);assert.equal(new TextDecoder().decode(inner.find(x=>x.no===99).v),'unknown');assert.equal(v.done[0].headers['Content-Length'],undefined);assert.equal(v.done[0].headers['grpc-encoding'],'identity');assert.ok(v.logs.includes('[airborne diag-v1] module-replaced'));assert.doesNotMatch(v.logs.join('\n'),/012345|private|token|signature|Authorization|https/i);}});
test('unknown or missing UA no-op; explicit flavors bypass UA safely',async()=>{for(const ua of ['', 'unknown/1']){let v=responseEnv({ua,argument:{diagnostics:true}});await A.run(v.e);assert.deepEqual(v.done,[{}]);assert.ok(v.logs.includes('[airborne diag-v1] module-unknown-ua'));}for(const [module,md] of [['universal','e5a968f1a5055bbe5c12e67b100a6dcb'],['hd','f993a054969a4f6ae6b20a65f1292e47'],['inter','8c3feda2e92bf60e8a7aeade1a231586']]){let v=responseEnv({ua:'unknown',argument:{module}});await A.run(v.e);assert.equal(selected(v),md);assert.deepEqual(v.logs,[]);}assert.equal(A.config({module:'invalid'}).module,'auto');});
test('response failure boundaries finish exactly once with safe logs',async()=>{for(const mutate of [e=>e.$argument.enabled=false,e=>e.$response.status=500,e=>e.$response.headers['content-encoding']='gzip',e=>e.$response.h2_trailers['grpc-status']='13',e=>e.$response.body=A.frame(A.f(4,'dm')),e=>e.$response.body=concat(e.$response.body,e.$response.body),e=>e.$response.body=Uint8Array.of(0),e=>e.$response.headers['grpc-encoding']='br',e=>e.$utils.ungzip=()=>{throw Error('token secret');},e=>e.$request.method='GET',e=>e.$request.url='https://evil.example/bilibili.app.view.v1.View/ViewProgress']){let v=responseEnv({gzip:true,argument:{diagnostics:true}});mutate(v.e);await A.run(v.e);assert.deepEqual(v.done,[{}]);assert.equal(v.calls.length,0);assert.doesNotMatch(v.logs.join('\n'),/secret|token|https|012345/i);}});
test('malformed or duplicated chronos and already patched remain unchanged',async()=>{for(const md5 of ['not-md5','e5a968f1a5055bbe5c12e67b100a6dcb']){let v=responseEnv({md5});await A.run(v.e);assert.deepEqual(v.done,[{}]);}let v=responseEnv();let p=A.f(2,concat(A.f(1,Object.keys(A.MODULES)[0]),A.f(2,'old')));v.e.$response.body=A.frame(concat(p,p));await A.run(v.e);assert.deepEqual(v.done,[{}]);});
