const test=require('node:test');
const assert=require('node:assert/strict');
const A=require('../scripts/airborne');
const join=(...p)=>Buffer.concat(p.map(x=>Buffer.from(x)));
const dm='https://grpc.biliapi.net/bilibili.community.service.dm.v1.DM/DmSegMobile';
const vp='https://app.bilibili.com/bilibili.app.viewunite.v1.View/ViewProgress';
function fixture(body=A.frame(A.f(99,'unknown')), query='empty'){
 const calls=[],done=[];
 const e={$argument:{},$request:{url:dm,method:'POST',headers:{'x-bili-moss-engine-type':'1'},body:A.frame(join(A.f(1,170001),A.f(2,456),A.f(3,1),A.f(4,1)))},$persistentStore:{read:()=>null,write:()=>true},$httpClient:{get:(o,cb)=>{calls.push(o);if(query==='fail')cb('network');else cb(null,{status:200},JSON.stringify(query==='rows'?[{cid:'456',category:'sponsor',actionType:'skip',segment:[0,114]}]:[]));},post:(o,cb)=>{calls.push(o);cb(null,{status:200,headers:{'grpc-encoding':'identity'}},body);}},$done:o=>done.push(o),setTimeout:()=>1,clearTimeout:()=>{}};
 return {e,calls,done};
}
for(const query of ['fail','empty'])for(const [name,body] of [['empty-body',new Uint8Array()],['short',Uint8Array.of(0)],['bad-protobuf',A.frame(Uint8Array.of(0))],['multi',join(A.frame(new Uint8Array()),A.frame(new Uint8Array()))]])test(`${query} invalid ${name} engine1 does not synthesize success`,async()=>{const v=fixture(body,query);await A.run(v.e);assert.deepEqual(v.done,[{}]);});
for(const query of ['fail','empty'])test(`${query} legal frame0 permits status repair`,async()=>{const body=A.frame(new Uint8Array()),v=fixture(body,query);await A.run(v.e);assert.equal(v.done[0].response.headers['grpc-status'],'0');assert.deepEqual(v.done[0].response.body,body);});
const chronos=()=>join(A.f(2,join(A.f(1,'0123456789abcdef0123456789abcdef'),A.f(2,'https://example.invalid/m.zip'))));
for(const loc of ['headers','h2_trailers'])for(const status of ['13','invalid','', '00'])test(`ViewProgress ${loc} status ${JSON.stringify(status)} no-op`,async()=>{const v=fixture();v.e.$request.url=vp;v.e.$request.headers={'user-agent':'bili-hd/3.0'};v.e.$response={status:200,headers:{},h2_trailers:{},body:A.frame(chronos())};v.e.$response[loc]={'grpc-status':status};await A.run(v.e);assert.deepEqual(v.done,[{}]);assert.equal(v.calls.length,0);});
for(const url of [dm.replace('grpc.biliapi.net','evil.example'),dm.replace('https:','http:'),dm+'?x=1',dm.replace('/bilibili.','/extra/bilibili.'),vp.replace('app.bilibili.com','evil.example'),vp+'?x=1'])test(`exact URL guard ${url}`,async()=>{const v=fixture();v.e.$request.url=url;if(url.includes('ViewProgress'))v.e.$response={status:200,headers:{},body:A.frame(chronos())};await A.run(v.e);assert.deepEqual(v.done,[{}]);assert.equal(v.calls.length,0);});
for(const ua of ['bili-hd-foo/3.0','bilibili-other/8.0','bili-inter-extra/3.0','bili-universal-other/8.0'])test(`reject pseudo UA ${ua}`,async()=>{assert.equal(A.chronos(chronos(),A.config({}),{'user-agent':`grpc-c++/1.0 ${ua}`}),null);});
test('rewritten binary removes hop headers and Connection nominated fields',async()=>{const v=fixture(undefined,'rows');const h={'Transfer-Encoding':'chunked',Connection:'X-Hop, Another','Keep-Alive':'timeout=5','proxy-connection':'keep-alive',Upgrade:'h2c','X-Hop':'secret',aNoThEr:'secret','Content-Length':'123','grpc-encoding':'identity','Content-Type':'application/grpc','X-End':'retained'};v.e.$httpClient.post=(o,cb)=>cb(null,{status:200,headers:h},A.frame(A.f(99,'original')));await A.run(v.e);assert.deepEqual(v.done[0].response.headers,{'Content-Type':'application/grpc','X-End':'retained','grpc-status':'0','grpc-encoding':'identity'});});
test('untouched compressed fallback keeps original grpc-encoding and bytes',async()=>{const body=Uint8Array.of(1,0,0,0,1,42),v=fixture(body,'fail');v.e.$utils={ungzip:()=>A.f(99,'valid')};v.e.$httpClient.post=(o,cb)=>cb(null,{status:200,headers:{'grpc-encoding':'gzip'}},body);await A.run(v.e);assert.equal(v.done[0].response.headers['grpc-encoding'],'gzip');assert.deepEqual(v.done[0].response.body,body);});
