/* SPDX-License-Identifier: MIT
 * Independent wire-preserving implementation. No upstream ad/VIP logic.
 */
(function(root){
'use strict';
const CATS=['sponsor','intro','outro','preview','selfpromo','interaction','filler','music_offtopic'];
const MAX=4*1024*1024, KEY='loon.airborne.v1.cache';
function bytes(x){if(x instanceof Uint8Array)return x;if(x instanceof ArrayBuffer)return new Uint8Array(x);throw Error('binary required');}
function join(parts){let size=parts.reduce((n,p)=>n+p.length,0);if(size>MAX)throw Error('oversize');let out=new Uint8Array(size),i=0;for(const p of parts){out.set(p,i);i+=p.length;}return out;}
function vi(n){n=BigInt(n);if(n<0n||n>0xffffffffffffffffn)throw Error('integer');const a=[];do{a.push(Number(n&127n)|(n>127n?128:0));n>>=7n;}while(n);return Uint8Array.from(a);}
function readvi(b,state){let n=0n;for(let i=0;i<10;i++){if(state.p>=b.length)throw Error('EOF');let v=b[state.p++];if(i===9&&v>1)throw Error('varint');n|=BigInt(v&127)<<BigInt(7*i);if(!(v&128))return n;}throw Error('varint');}
function fields(input){let b=bytes(input);if(b.length>MAX)throw Error('oversize');const st={p:0},out=[];while(st.p<b.length){let start=st.p,t=readvi(b,st),no=Number(t>>3n),w=Number(t&7n),v;if(!no||no>536870911)throw Error('tag');if(w===0)v=readvi(b,st);else if(w===2){let n=Number(readvi(b,st));if(!Number.isSafeInteger(n)||n>b.length-st.p)throw Error('length');v=b.slice(st.p,st.p+n);st.p+=n;}else if(w===1||w===5){st.p+=w===1?8:4;if(st.p>b.length)throw Error('EOF');}else throw Error('unsupported wire');out.push({no,w,v,raw:b.slice(start,st.p)});}return out;}
function f(no,value){let b=typeof value==='string'?new TextEncoder().encode(value):value;return typeof value==='bigint'||typeof value==='number'?join([vi(no*8),vi(value)]):join([vi(no*8+2),vi(b.length),b]);}
function one(fs,no,w){let a=fs.filter(x=>x.no===no&&x.w===w);if(a.length!==1)throw Error('missing/duplicate field');return a[0].v;}
function frame(b){return join([Uint8Array.of(0,(b.length>>>24)&255,(b.length>>>16)&255,(b.length>>>8)&255,b.length&255),b]);}
function frames(input,encoding,ungzip){let b=bytes(input),p=0,out=[];if(b.length>MAX)throw Error('oversize');while(p<b.length){if(b.length-p<5)throw Error('grpc header');let flag=b[p],n=b[p+1]*16777216+b[p+2]*65536+b[p+3]*256+b[p+4];p+=5;if(n>b.length-p||flag>1)throw Error('grpc frame');let payload=b.slice(p,p+n);p+=n;if(flag){if(encoding!=='gzip'||!ungzip)throw Error('compression');payload=bytes(ungzip(payload));if(payload.length>MAX)throw Error('inflated size');}out.push(payload);if(out.length>64)throw Error('frame count');}if(!out.length)throw Error('empty grpc');return out;}
function header(h,k){for(const n of Object.keys(h||{}))if(n.toLowerCase()===k)return String(h[n]).toLowerCase();return '';}
function cleanHeaders(h){let o={};for(const k of Object.keys(h||{}))if(!['content-length','content-encoding','grpc-encoding'].includes(k.toLowerCase()))o[k]=h[k];o['grpc-encoding']='identity';return o;}
function bv(aid){let n=((1n<<51n)|BigInt(aid))^23442827791579n;const table='FcwAPNKTMug3GV5Lj7EJnHpWsx4tb8haYeviqBz6rkCy12mUSDQX9RdoZf',a=Array.from('BV1000000000');for(let i=11;n>0n;i--){if(i<3)throw Error('aid');a[i]=table[Number(n%58n)];n/=58n;}[a[3],a[9]]=[a[9],a[3]];[a[4],a[7]]=[a[7],a[4]];return a.join('');}
function config(a){a=a&&typeof a==='object'?a:{};let num=(k,d,min,max)=>{let n=Number(a[k]??d);return Number.isFinite(n)?Math.min(max,Math.max(min,n)):d;};return {enabled:a.enabled!==false&&a.enabled!=='false',categories:CATS.filter(k=>a[k]===true||a[k]==='true'||(a[k]===undefined&&k==='sponsor')),min:num('minDuration',8,0,3600),offset:num('offset',2,-10,10),ttl:num('cacheTTL',3600,60,86400)*1000,capacity:Math.floor(num('cacheCapacity',64,1,256))};}
function normalize(rows,cid,c){if(!Array.isArray(rows)||rows.length>10000)throw Error('segments shape');let out=[];for(const r of rows){if(!r||String(r.cid)!==String(cid)||!c.categories.includes(r.category)||r.actionType!=='skip'||!Array.isArray(r.segment)||r.segment.length!==2)continue;let [s,e]=r.segment;if(typeof s!=='number'||typeof e!=='number'||!Number.isFinite(s)||!Number.isFinite(e)||s<0||e<=s||e>2147483||e-s<c.min)continue;let start=Math.max(0,s+c.offset);if(start>=e)continue;out.push([Math.round(start*1000),Math.round(e*1000)]);}out.sort((a,b)=>a[0]-b[0]||a[1]-b[1]);let merged=[];for(const r of out){let last=merged[merged.length-1];if(last&&r[0]<=last[1])last[1]=Math.max(last[1],r[1]);else merged.push(r);}return merged;}
function cacheLoad(store,now,c){try{let v=JSON.parse(store.read(KEY)||'{}');if(v.v!==1||!Array.isArray(v.entries))return [];return v.entries.filter(e=>e&&typeof e.k==='string'&&Number.isFinite(e.t)&&e.t<=now&&now-e.t<c.ttl&&Array.isArray(e.rows)).sort((a,b)=>a.t-b.t).slice(-c.capacity);}catch(_){return [];}}
function cacheSave(store,entries){try{let data=JSON.stringify({v:1,entries});while(data.length>2*1024*1024&&entries.length){entries=entries.slice(1);data=JSON.stringify({v:1,entries});}store.write(data,KEY);}catch(_){} }
function elem(s,e,cid){let id=900000000+Math.floor(s);return join([f(1,id),f(2,s),f(3,5),f(4,50),f(5,16777215),f(6,'1948dd5d'),f(7,'空指部已就位'),f(8,1735660800),f(9,11),f(10,'airborne:'+e),f(12,String(id)),f(13,1310724),f(25,1),f(26,BigInt(cid)),f(27,1)]);}
function inject(payload,ranges,cid){let fs=fields(payload),actions=new Set();for(const x of fs)if(x.no===1&&x.w===2){for(const e of fields(x.v))if(e.no===10&&e.w===2)actions.add(new TextDecoder().decode(e.v));}return join([payload,...ranges.filter(r=>!actions.has('airborne:'+r[1])).map(r=>f(1,elem(r[0],r[1],cid)))]);}
const MODULES={'45b564f5ba1fdd3746406937059addd8':'e5a968f1a5055bbe5c12e67b100a6dcb','c29bd8f2b64a8f57f49c3622c0f763db':'ecca73e42e160074e0caf4b3ddb54a52','c218977c14e5dfdafd51edf3ae49ed02':'f993a054969a4f6ae6b20a65f1292e47','8232ffb6ee43b687b5fe5add5b3e97de':'feaca416bbc1174b8e935cf87ff8f0b5','325e7073ffc6fb5263682fecdcd1058f':'932002070dc1b51241198a074d2279fc','3a14beddd23328eaddfe9f0eb048d713':'8c3feda2e92bf60e8a7aeade1a231586'};
const MODULE_BASE='https://raw.githubusercontent.com/kokoryh/chronos/69a8996b1f1311b606021e3f194b0390280ab618/';
function chronos(payload){let fs=fields(payload),cs=fs.filter(x=>x.no===2&&x.w===2);if(cs.length!==1)return null;let inner=fields(cs[0].v),md5=new TextDecoder().decode(one(inner,1,2)),next=MODULES[md5];if(!next)return null;let replacement=join([f(1,next),f(2,MODULE_BASE+next+'.zip'),...inner.filter(x=>![1,2,3].includes(x.no)).map(x=>x.raw)]);return join(fs.map(x=>x===cs[0]?f(2,replacement):x.raw));}
function fetchHTTP(env,method,opts){return new Promise((resolve,reject)=>{let settled=false;const timer=env.setTimeout(()=>{if(!settled){settled=true;reject(Error('timeout'));}},3500);env.$httpClient[method](Object.assign({timeout:3000,'auto-cookie':false},opts),(error,response,body)=>{if(settled)return;settled=true;env.clearTimeout(timer);if(error)reject(Error('network'));else resolve({response:response||{},body});});});}
async function run(env){let finished=false;const done=o=>{if(!finished){finished=true;env.$done(o||{});}};const watchdog=env.setTimeout(()=>done({}),8500);try{const c=config(env.$argument);if(!c.enabled)return done({});const req=env.$request;const unzip=env.$utils&&env.$utils.ungzip?b=>env.$utils.ungzip(b):null;
 if(env.$response){if(!/\/bilibili\.app\.view(?:unite)?\.v1\.View\/ViewProgress$/.test(req.url)||!c.categories.length||Number(env.$response.status)!==200)return done({});if(header(env.$response.headers,'content-encoding')&&!['identity'].includes(header(env.$response.headers,'content-encoding')))return done({});const ps=frames(env.$response.body,header(env.$response.headers,'grpc-encoding'),unzip);let changed=false;const result=ps.map(p=>{let q=chronos(p);if(q)changed=true;return frame(q||p);});return done(changed?{body:join(result),headers:cleanHeaders(env.$response.headers)}:{});}
 if(!/\/bilibili\.community\.service\.dm\.v1\.DM\/DmSegMobile$/.test(req.url)||req.method!=='POST'||!c.categories.length)return done({});const ps=frames(req.body,header(req.headers,'grpc-encoding'),unzip);if(ps.length!==1)return done({});const fs=fields(ps[0]),aid=one(fs,1,0),cid=one(fs,2,0),type=one(fs,3,0),index=one(fs,4,0);if(type!==1n||aid<=0n||aid>=(1n<<51n)||cid<=0n||index<1n||index>100000n)return done({});let video=bv(aid),now=Date.now(),entries=cacheLoad(env.$persistentStore,now,c),key=video+'|'+cid+'|'+c.categories.join(','),hit=entries.find(e=>e.k===key),rows;
 if(hit)rows=hit.rows;else{const url='https://bsbsb.top/api/skipSegments?videoID='+encodeURIComponent(video)+'&cid='+cid+'&categories='+encodeURIComponent(JSON.stringify(c.categories));let r=await fetchHTTP(env,'get',{url,headers:{origin:'https://github.com/beckyeeky/loon-bilibili-airborne','x-ext-version':'0.1.0-beta'}});let status=Number(r.response.status);if(status===404)rows=[];else if(status===200){if(typeof r.body!=='string'||r.body.length>1024*1024)throw Error('JSON size');rows=JSON.parse(r.body);normalize(rows,cid,c);}else return done({});entries.push({k:key,t:now,rows});cacheSave(env.$persistentStore,entries.slice(-c.capacity));}
 const begin=Number(index-1n)*360000,end=begin+360000;let ranges=normalize(rows,cid,c).filter(r=>r[0]>=begin&&r[0]<end);if(!ranges.length)return done({});const reply=await fetchHTTP(env,'post',{url:req.url,headers:req.headers,body:req.body,'binary-mode':true,alpn:'h2'});if(Number(reply.response.status)!==200)return done({});if(header(reply.response.headers,'content-encoding')&&!['identity'].includes(header(reply.response.headers,'content-encoding')))return done({});if(header(reply.response.h2_trailers,'grpc-status')&&!['0'].includes(header(reply.response.h2_trailers,'grpc-status')))return done({});let rp=frames(reply.body,header(reply.response.headers,'grpc-encoding'),unzip);if(rp.length!==1)return done({});let body=frame(inject(rp[0],ranges,cid));return done({response:{status:200,headers:cleanHeaders(reply.response.headers),h2_trailers:reply.response.h2_trailers||{},body}});
 }catch(_){done({});}finally{env.clearTimeout(watchdog);}}
const API={CATS,fields,f,frame,frames,bv,config,normalize,cacheLoad,cacheSave,inject,chronos,run,KEY,MODULES,MODULE_BASE};
if(typeof module!=='undefined'&&module.exports)module.exports=API;else run(root);
})(globalThis);
